djangocrud/urls.py
from django.contrib import admin
from django.urls import include, path
from tasks import views 


urlpatterns = [
    path('admin/', admin.site.urls),
    # path(include('tasks.urls')),
    path('tasks/', include('tasks.urls')),
    path('',views.home, name="home"),
    path('signup/', views.signup, name="signup"),
    path('tasks/', views.tasks, name="tasks"),
    path('tasks_completed/', views.list_tasks_completed, name="tasks_completed"),
    path('tasks/<int:id>/',views.task_detail, name="task_detail"),
    path('tasks/delete/<int:id>',views.task_delete, name="task_delete"),
    path('tasks/complete/<int:id>',views.task_complete, name="task_complete"),
    path('logout/',views.user_logout, name="logout"),
    path('login/',views.user_login, name="login"), # "signin"  
    path('tasks/create/',views.create_task, name="create_task")
]

tasks/urls.py
from django.urls import path
from . import views


urlpatterns = [
    # path('', views.index),
]

tasks/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model):
    title = models.CharField(max_length = 200) 
    description = models.TextField(blank = True, max_length=200)
    completed = models.BooleanField(default = False)
    created_at = models.DateTimeField(auto_now_add = True)
    date_completed = models.DateTimeField(null = True, blank= True)
    important = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE) 
    
    def __str__(self):
        return self.title + ' - by: ' + self.user.username

tasks/forms.py
from django.forms import ModelForm
from .models import Task

class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ['title','description','important','completed']
        # se puede personalizar con la propiedad "widget = "

tasks/views.py
from django.db import IntegrityError
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from .forms import TaskForm
from .models import Task
from django.utils import timezone
from django.contrib.auth.decorators import login_required

# def login(request):
#     return render(request, 'login.html',{
#         'form' : UserCreationForm
#     })
    
def home(request):
    return render(request, 'home.html')


def signup(request):
    if request.method == "GET":
         return render(request, 'signup.html',{
        'form' : UserCreationForm
    })
    else: #si es POST...
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(request.POST['username'], password=request.POST['password1'])
                login(request,user)
                print("usuario creado, redireccinoando a tasks....")
                return redirect('home')
            except IntegrityError: 
                return render(request, 'signup.html' ,{
                    'form' : UserCreationForm,
                    'error' : 'User already exists'
                })
        return render(request, 'signup.html',{
            'form' : UserCreationForm,
            'error' : 'Password error, please try again'
        })


@login_required      
def tasks(request):
    tasks = Task.objects.filter(user=request.user,date_completed__isnull = True) #filtrar siempre desde la consulta y no en la vista (template)
    return render(request, 'tasks.html',{
        'tasks' : tasks
    })


@login_required
def task_detail(request,id):
    if request.method == 'GET':
        task = get_object_or_404(Task, pk=id, user=request.user) #obtenemos un task específico por su id y del usuario
        form = TaskForm(instance=task) # pasamos task especifico para poder editarlo
        return render(request, 'task_detail.html',{
            'task' : task,
            'form' : form
        })
    else: #si es POST:
        try:
            task = get_object_or_404(Task, pk=id, user=request.user) #obtenemos el id
            form = TaskForm(request.POST, instance=task) #a través de instance pasamos el id y luego guardamos
            if form.is_valid():
                task.save()
                return redirect('tasks')
            else:
                return render(request, 'task_detail.html', {
                    'form': form,
                    'error': 'Form is not valid'
                })
        except Exception as e:
            return render(request, 'task_detail.html', {
                'form': TaskForm(),
                'error': str(e)
            })


@login_required
def create_task(request):
    if request.method == 'GET':
        return render(request, 'create_task.html', {
            'form': TaskForm()
        })
    else:  # si es POST
        try:
            form = TaskForm(request.POST)
            if form.is_valid():
                task = form.save(commit=False)
                task.user = request.user
                task.save()
                return redirect('tasks')
            else:
                return render(request, 'create_task.html', {
                    'form': form,
                    'error': 'Form is not valid'
                })
        except Exception as e:
            return render(request, 'create_task.html', {
                'form': TaskForm(),
                'error': str(e)
            })
            
@login_required        
def task_delete(request, id):
    task = get_object_or_404(Task, pk=id)
    task.delete()
    return redirect('tasks')


@login_required
def task_complete(request,id):
    task = get_object_or_404(Task,pk=id, user=request.user)
    try:
        if request.method == 'POST':
            task.completed = True 
            task.date_completed = timezone.now()
            task.save()
            return redirect('tasks')
    except Exception as e:
        return redirect ('task',{
            'error' : 'error al eliminar task'
        })
    
    
@login_required
def list_tasks_completed (request):
    tasks_completed = Task.objects.filter(user= request.user,date_completed__isnull = False).order_by('-date_completed') # uso de field Lookup: "__isnull"
    return render(request, 'tasks_completed.html',{
        'tasks_completed' : tasks_completed
    })


@login_required
def user_logout(request):
    logout(request)
    return redirect('home')


#ESTAMOS EL LOGIN METHOD "sigin"
def user_login(request):
    if request.method == "GET":
        return render(request, 'login.html', {
            'form': AuthenticationForm()
        })
    else: # si es POST
        user = authenticate(request, username=request.POST['username'],password= request.POST['password'])
        if user is None:
            return render(request, 'login.html', {
                'form': AuthenticationForm(),
                'error': 'Invalid username or password'
            })
        else:
            login(request,user)
            return redirect('home')

        
    
        

tasks/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>🌐 Django crud app!</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">Django Crud App</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home' %}">Home</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tasks' %}">Tasks Pending</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tasks_completed' %}">Tasks Completed</a>
                    </li>
                    {% endif %}
                </ul>
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% block content %}
    {% endblock %}

</body>
</html>

tasks/templates/create_task.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-5">
    <h1 class="text-center">Create Task</h1>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form action="/tasks/create/" method="post" class="p-4 border rounded shadow-sm bg-light">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_title">Title</label>
                    <input type="text" name="title" class="form-control" id="id_title" required>
                </div>
                <div class="form-group mt-3">
                    <label for="id_description">Description</label>
                    <textarea name="description" class="form-control" id="id_description" rows="3"></textarea>
                </div>
                <div class="form-group form-check mt-3">
                    <input type="checkbox" name="important" class="form-check-input" id="id_important">
                    <label class="form-check-label" for="id_important">Important</label>
                </div>
                <div class="text-center">
                    <button type="submit" class="btn btn-primary mt-3">Create Task!</button>
                </div>
            </form>
            {% if error %}
                <div class="alert alert-danger mt-3">{{ error }}</div>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

tasks/templates/home.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-5">
    <div class="jumbotron text-center bg-info text-white py-5">
        <h1 class="display-3">Welcome to My Django Portfolio!</h1>
        <p class="lead">Showcasing my skills and projects with Django.</p>
        <hr class="my-4 bg-light">
        <p>Explore the features and functionalities of this application.</p>
        <a class="btn btn-light btn-lg mb-2" href="https://github.com/Joaquin3312" role="button">Visit My GitHub</a>
        <a class="btn btn-dark btn-lg mb-2" href="https://www.linkedin.com/in/joaquin-ignacio-pinto-reynolds-501b6325b" role="button">Connect on LinkedIn</a>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="card mb-4 shadow-sm">
                <div class="card-body">
                    <h5 class="card-title">Tasks pending</h5>
                    <p class="card-text">Organize and record all your tasks</p>
                    <a href="{% url 'tasks' %}" class="btn btn-primary">View details</a>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card mb-4 shadow-sm">
                <div class="card-body">
                    <h5 class="card-title">Tasks completed</h5>
                    <p class="card-text">all your completed tasks in one place.</p>
                    <a href="{% url 'tasks_completed' %}" class="btn btn-primary">View details</a>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card mb-4 shadow-sm">
                <div class="card-body">
                    <h5 class="card-title">Blog</h5>
                    <p class="card-text">cooming soon..</p>
                    <a href="#" class="btn btn-primary">View details</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

tasks/templates/login.html
<!-- "signin" -->

{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header text-center">
                    <h1>Login</h1>
                </div>
                <div class="card-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <div class="form-group">
                                <label for="username">Username</label>
                                <input type="text" class="form-control" id="username" name="username" required>
                            </div>
                            <div class="form-group">
                                <label for="password">Password</label>
                                <input type="password" class="form-control" id="password" name="password" required>
                            </div>
                        </div>
                        <div class="text-center">
                            <button type="submit" class="mt-2 btn btn-primary btn-block">Ingresar</button>
                        </div>
                    </form>
                    {% if error %}
                        <div class="alert alert-danger mt-3">
                            {{ error }}
                        </div>
                    {% endif %}
                </div>
                <div class="card-footer text-center">
                    <p>Don't have an account and want to sign up?</p>
                    <a href="{% url 'signup' %}" class="btn btn-link">Sign Up</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

tasks/templates/signup.html
{% extends 'base.html' %}
{% block content %}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header text-center">
                    <h1>Sign up!</h1>
                </div>
                <div class="card-body">
                    {% if error %}
                        <div class="alert alert-danger" role="alert">
                            {{ error }}
                        </div>
                    {% endif %}
                    <form action="/signup/" method="POST">
                        {% csrf_token %}
                        <div class="">
                            <div class="form-group">
                                <label for="id_username">Username</label>
                                <input type="text" class="form-control" id="id_username" name="username" required>
                            </div>
                            <div class="form-group">
                                <label for="id_password1">Password</label>
                                <input type="password" class="form-control" id="id_password1" name="password1" required>
                            </div>
                            <div class="form-group">
                                <label for="id_password2">Confirm Password</label>
                                <input type="password" class="form-control" id="id_password2" name="password2" required>
                            </div>
                        </div>
                        <div class="container d-flex align-items-center justify-content-center">
                            <button type="submit" class=" btn btn-primary btn-block text-center mt-2">Sign Up</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock  %}

tasks/templates/task_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-5">
    <h1 class="text-center">Update Task</h1>
    <div class="row justify-content-center">
        <div class="col-md-6">
            {% if error %}
                <div class="alert alert-danger">{{ error }}</div>
            {% endif %}
            <form action="" method="post" class="p-4 border rounded shadow-sm bg-light">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_title">Title</label>
                    <input type="text" name="title" class="form-control" id="id_title" value="{{ form.title.value }}" required>
                </div>
                <div class="form-group mt-3">
                    <label for="id_description">Description</label>
                    <textarea name="description" class="form-control" id="id_description" rows="3">{{ form.description.value }}</textarea>
                </div>
                <div class="form-group form-check mt-3">
                    <input type="checkbox" name="important" class="form-check-input" id="id_important" {% if form.important.value %}checked{% endif %}>
                    <label class="form-check-label" for="id_important">Important</label>
                </div>
                <div class="form-group text-center mt-3">
                    <button type="submit" class="btn btn-primary btn-lg">Update</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

tasks/templates/tasks.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h2 class="mb-4 p-2 rounded bg-info-subtle">Tasks Pending</h2>    
    <div class="row mb-3">
        <div class="col-8">
            <h4>Lista de tareas</h4>
        </div>
        <div class="col-4 text-end">
            <a href="{% url 'create_task' %}" class="btn btn-primary">Create Task</a>
        </div>
    </div>
    <ul class="list-group">
        {% for task in tasks %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
            <div>
                {% if task.important == True %}
                    🛑
                {% endif %}
                <a href="{% url 'task_detail' task.id %}" class="h5">{{ task.title }}</a>
            </div>
            <div class="btn-group" role="group">
                <form action="{% url 'task_delete' task.id %}" method="post" class="d-inline" style="margin-right: 5px;">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                </form>
                <form action="{% url 'task_complete' task.id %}" method="post" class="d-inline">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-success btn-sm">Complete Task ✅</button>
                </form>
            </div>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

tasks/templates/tasks_completed.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-5 mb-4">
    <h2 class="mb-4 p-2 rounded bg-success-subtle">Tasks Completed</h2>
    <ul class="list-group">
        {% for task in tasks_completed %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
            <div>
            <h3>✅ {{ task.title }}</h3>
            <p>{{ task.description }}</p>
            <p>Completed at: {{ task.date_completed|date:'F j, Y, g:i a' }}</p>
            </div>
            <form action="{% url 'task_delete' task.id %}" method="post" class="ml-3">
                {% csrf_token%}
                <button type="submit" class="btn btn-danger">Delete task</button>
            </form>
        </li>
        {% endfor %}
    </ul>
</div>

{% endblock %}